########################## vars.yml ######################################################################
##########################  Temporary Folder #############################################################
#temp_folder: "C:\\Temp\\Ansible-P1"
#temp_path: "C:\\Temp"
########################## Git Configuration ##############################################################
#git_installer_url: "https://github.com/git-for-windows/git/releases/download/v2.43.0.windows.1/Git-2.43.0-64-bit.exe"
#git_install_directory: "C:\\Program Files\\Git"
######################### Installer Paths #################################################################
#git_installer: "C:\\Temp\\GitInstaller.exe"
##########################################################################################################

    - name: Check if Temp folder exists
      win_stat:
          path: "{{ temp_path }}"
      register: temp_folder_stat

    - name: Create Temp folder if it doesn't exist
      win_file:
        path: "{{ temp_path }}"
        state: directory
      when: not temp_folder_stat.stat.exists

    - name: Check if Git is installed
      win_command: git --version
      register: git_check
      ignore_errors: true

    - name: Download Git installer
      win_get_url:
        url: "{{ git_installer_url }}"
        dest: "{{ git_installer_path }}"
      when: git_check.rc != 0

    - name: Install Git
      win_shell: Start-Process -Wait -FilePath "{{ git_installer_path }}" -ArgumentList "/VERYSILENT /NORESTART /SUPPRESSMSGBOXES"
      when: git_check.rc != 0

    - name: Check if Git is installed (after installation)
      win_command: git --version
      register: git_check_after_install
      when: git_check.rc != 0

    - name: Delete Git installer
      win_shell: Remove-Item -Path "{{ git_installer_path }}" -Force
      when: git_check.rc != 0

