####################################################################################################################
#                                       vars.yml                                                                   # 
#                                                                                                                  #
#     #Temporary Folder                                                                                            #
#    PythonInstaller_temp_folder: "C:\\Temp\\PythonInstaller"                                                                      #
#    PythonInstaller_temp_path: "C:\\Temp\\PythonInstaller" 
#    python_installer: "C:\\Temp\\PythonInstaller\\python_installer.exe"                                                                                       #
#                                                                                                                  #
#    #Python Configuration                                                                                         #
#     ansible_python_interpreter: "C:\\Python312\\python.exe"                                                      #
#     python_installation_path: "C:\\Python312\\python.exe"                                                        #
#     python_installer_url: "https://www.python.org/ftp/python/3.12.0/python-3.12.0-amd64.exe"                     #
#                                                                                                                  #
#     #Python Installation Check                                                                                   #
#     python_installation_check: "C:\\Python312\\python.exe"                                                       #
#                                                                                                                  #
#                                                                                                                  #
#                                                                                                                  #
####################################################################################################################


    - name: Check if Temp folder exists
      win_stat:
      path: "{{ PythonInstaller_temp_path }}"
      register: temp_folder_stat

    - name: Create Temp folder if it doesn't exist
      win_file:
        path: "{{ PythonInstaller_temp_path }}"
        state: directory
      when: not temp_folder_stat.stat.exists
  
    - name: Check if Python is installed
      win_shell: python --version
      register: python_check
      ignore_errors: true

    - name: Download Python installer
      win_get_url:
        url: "{{ python_installer_url }}"
        dest: "{{ python_installer }}"
      when: python_check.rc != 0

    - name: Install Python
      win_shell: Start-Process -Wait -FilePath "{{ python_installer }}" -ArgumentList "/quiet", "InstallAllUsers=1", "PrependPath=1"
      when: python_check.rc != 0

    - name: Check if Python is installed (after installation)
      win_shell: Test-Path "{{ python_installation_check }}"
      register: python_check_after_install
      when: python_check.rc != 0

    - name: Delete Python installer
      win_shell: Remove-Item -Path "{{ python_installer }}" -Force
      when: python_check.rc != 0

