# group_vars/production/windows_servers/main_tasks_vars.yml
---
include_tempfolder_tasks: true
include_python_tasks: true
include_git_tasks: true
include_drive_letter_tasks: true
include_setup_disk_tasks: true
