---
- name: Clone or pull Ansible-p1 from Git repository
  win_shell: |
    if (Test-Path -Path "{{ temp_folder }}") {
      Set-Location -Path "{{ temp_folder }}"
      if (Test-Path .git) {
        git pull
        Write-Host 'Repository inside the folder updated with the latest changes.'
      } else {
        Write-Host 'The folder exists but is not a Git repository. Cloning...'
        Remove-Item -Path "{{ temp_folder }}" -Recurse -Force
        git clone "{{ git_repo_url | regex_replace('https://', 'https://'+git_access_token+'@') }}" "{{ temp_folder }}"
        Write-Host 'Repository cloned into the folder for the first time.'
      }
    } else {
      Write-Host 'Cloning the Git repository for the first time...'
      git clone "{{ git_repo_url | regex_replace('https://', 'https://'+git_access_token+'@') }}" "{{ temp_folder }}"
    }
  args:
    executable: powershell.exe


  # - name: Cloning Ansible-p1 from Git repository
  #   win_shell: |
  #     if (Test-Path -Path "{{ temp_folder }}") {
  #       Remove-Item -Path "{{ temp_folder }}" -Recurse -Force
  #     }
  #     git clone "{{ git_repo_url | regex_replace('https://', 'https://'+git_access_token+'@') }}" "{{ temp_folder }}"
  #   args:
  #     executable: powershell.exe
