---
  - name: Cloning Ansible-p1 from Git repository
    win_shell: |
      if (Test-Path -Path "{{ temp_folder }}") {
        Remove-Item -Path "{{ temp_folder }}" -Recurse -Force
      }
      git clone "{{ git_repo_url | regex_replace('https://', 'https://'+git_access_token+'@') }}" "{{ temp_folder }}"
    args:
      executable: powershell.exe
