# current path: roles/windows_servers/tasks/main.yml
# group_vars/production/windows_servers/main_tasks_vars.yml
# control true or false in main_tasks_vars.yml
# include task variables to true, the task will execute | default(true)
# include task variables to flase, the task will not execute | default(false)

---
- name: Include tasks for Setup Temp Folder on Windows
  include_tasks: SetTempFolder.yml
  when: include_tempfolder_tasks | default(true)

- name: Include tasks for Python on Windows
  include_tasks: PythonOnWin.yml
  when: include_python_tasks | default(false)

- name: Include tasks for Git on Windows
  include_tasks: GitOnWin.yml
  when: include_git_tasks | default(false)

- name: Include tasks for cloning ansible project from github
  include_tasks: GitCloneAnsible.yml
  when: include_GitCloneAnsible_tasks | default(false)

- name: Include tasks to change drive letter
  include_tasks: ChangeWinDriveLetter.yml
  when: include_drive_letter_tasks | default(false)

- name: Include tasks for setting up Windows disk
  include_tasks: SetupAutoWinDisk.yml
  when: include_setup_disk_tasks | default(false)


# Tasks for running Python script on Python servers
- name: Include tasks for running run_py_script.yml on python_servers
  include_tasks: run_py_script.yml
  when: include_run_py_script_tasks | default(false)
  ignore_errors: true
  register: test_result

- name: Include tasks for Add a line in DiskManagerConfig.xml (if run_py_script.yml succeeded)
  include_tasks: AddXmlElement.yml
  when: 
    - include_AddXmlElement_tasks | default(false)
    - test_result is defined
    - not test_result.failed
    - test_result.rc == 0

# Tasks for deleting/removing cloned Ansible project from Windows
- name: Include tasks for deleting/removing cloned Ansible project from Win
  include_tasks: RMGitCloneAnsible.yml
  when: include_RMGitCloneAnsible_tasks | default(false)

# - name: Include tasks for running run_py_script.yml on python_servers
#   include_tasks: run_py_script.yml
#   when: include_run_py_script_tasks | default(false)
#   ignore_errors: true
#   run_once: true
#   register: test_result

# - name: Include tasks for running run_py_script.yml on python_servers
#   include_tasks: run_py_script.yml
#   when: include_run_py_script_tasks | default(false)
#   ignore_errors: true
#   register: test_result

# - name: Include tasks for Add a line in DiskManagerConfig.xml (if test.yml succeeded)
#   include_tasks: AddXmlElement.yml
#   when: 
#     - include_AddXmlElement_tasks | default(false)
#     - test_result is defined
#     - test_result.failed == false
#     - test_result.rc == 0

# - name: Include tasks for Add a line in DiskManagerConfig.xml
#   include_tasks: AddXmlElement.yml
#   when: include_AddXmlElement_tasks | default(false)

# - name: Include tasks for deleting/ removing cloned ansible project from Win
#   include_tasks: RMGitCloneAnsible.yml
#   when: include_RMGitCloneAnsible_tasks | default(false)
