---
    - name: Add hosts to python_servers group
      add_host:
        name: connecting to python server
        groups: python_servers
      loop: "{{ groups['python_servers'] }}"
      when: include_run_py_script_tasks | default(false)

    - name: Check if Temp folder exists
      win_stat:
        path: "{{ temp_path }}"
      register: temp_folder_stat

    - name: Create Temp folder if it doesn't exist
      win_file:
        path: "{{ temp_path }}"
        state: directory
      when: not temp_folder_stat.stat.exists

    - name: Check if Python is installed
      win_shell: python --version
      register: python_check
      ignore_errors: true

    - name: Download Python installer
      win_get_url:
        url: "{{ python_installer_url }}"
        dest: "{{ python_installer }}"
      when: python_check.rc != 0

    - name: Install Python
      win_shell: Start-Process -Wait -FilePath "{{ python_installer }}" -ArgumentList "/quiet", "InstallAllUsers=1", "PrependPath=1"
      when: python_check.rc != 0

    - name: Check if Python is installed (after installation)
      win_shell: Test-Path "{{ python_installation_check }}"
      register: python_check_after_install
      when: python_check.rc != 0

    - name: Delete Python installer
      win_shell: Remove-Item -Path "{{ python_installer }}" -Force
      when: python_check.rc != 0



    - name: Check if Git is installed
      win_command: git --version
      register: git_check
      ignore_errors: true

    - name: Download Git installer
      win_get_url:
        url: "{{ git_installer_url }}"
        dest: "{{ git_installer_path }}"
      when: git_check.rc != 0

    - name: Install Git
      win_shell: Start-Process -Wait -FilePath "{{ git_installer_path }}" -ArgumentList "/VERYSILENT /NORESTART /SUPPRESSMSGBOXES"
      when: git_check.rc != 0

    - name: Check if Git is installed (after installation)
      win_command: git --version
      register: git_check_after_install
      when: git_check.rc != 0

    - name: Delete Git installer
      win_shell: Remove-Item -Path "{{ git_installer_path }}" -Force
      when: git_check.rc != 0

    - name: Cloning Ansible-p1 from Git repository
      win_shell: |
        if (Test-Path -Path "{{ temp_folder }}") {
          Remove-Item -Path "{{ temp_folder }}" -Recurse -Force
        }
        git clone "{{ git_repo_url | regex_replace('https://', 'https://'+git_access_token+'@') }}" "{{ temp_folder }}"
      args:
        executable: powershell.exe


    - name: Copy Python script to temp
      win_shell: Copy-Item -Path "{{ temp_folder }}{{ run_py_script_path }}" -Destination "{{ temp_path }}" -Force

    # - name: Display running processes before executing Python script
    #   win_shell: Get-Process | grep python
    #   register: processes_before

    - name: Execute Python script
      win_shell: python "{{ temp_path }}\{{ run_py_script_path }}"
      args:
        executable: powershell.exe
      register: python_script_output

    # - name: Display running processes after executing Python script
    #   win_shell: Get-Process | grep python
    #   register: processes_after

    - name: Display Python script output
      debug:
        var: python_script_output.stdout_lines

    - name: Save Python script output to a file
      lineinfile:
        path: /home/mmanoj/Ansible-P1/roles/windows_servers_role/files/output_file.txt
        create: yes
        line: "{{ python_script_output.stdout_lines | join('\n') }}"
      when: python_script_output.rc == 0


    - name: Delete Git cloned Ansible-p1 repository from Win
      win_shell: Remove-Item -Path "{{ temp_folder }}" -Recurse -Force
      args:
        executable: powershell.exe


# shell
# ---
# - name: Copy Python script to temp
#   copy:
#     src: "{{ temp_folder }}{{ run_py_script_path }}"
#     dest: "{{ temp_path }}"
#     mode: '0755'  # Ensure the script is executable

# - name: Display running processes before executing Python script
#   shell: ps aux
#   register: processes_before

# - name: Execute Python script
#   command: "{{ temp_path }}/{{ run_py_script_path }}"
#   register: python_script_output

# - name: Display running processes after executing Python script
#   shell: ps aux
#   register: processes_after

# - name: Display Python script output
#   debug:
#     var: python_script_output.stdout_lines



# - name: Copy Python script to temp
#   win_shell: |
#     Copy-Item -Path "{{ temp_folder }}{{ run_py_script_path }}" -Destination "{{ temp_path }}" -Force
#   args:
#     executable: powershell.exe

# - name: Execute Python script
#   win_shell: |
#     python "{{ temp_path }}\{{ run_py_script_name }}"
#   args:
#     executable: powershell.exe

# - name: Delete Python script file
#   win_shell: Remove-Item -Path "{{ temp_path }}\{{ run_py_script_name }}" -Force
#   args:
#     executable: powershell.exe


