# group_vars/production/windows_servers/script_vars.yml
---
    - name: Copy SetupAutoWinDisk.ps1 to temp
      win_shell: |
        Copy-Item -Path "{{ temp_folder }}{{ SetupAutoWinDisk_script_path }}" -Destination "{{ temp_path }}" -Force
      args:
        executable: powershell.exe

    - name: Execute PowerShell script
      win_shell: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        . "{{ temp_path }}\{{ SetupAutoWinDisk_script_name }}"
      args:
        executable: powershell.exe

    - name: Delete SetupAutoWinDisk.ps1 PowerShell script file
      win_shell: Remove-Item -Path "{{ temp_path }}\{{ SetupAutoWinDisk_script_name }}" -Force
      args:
        executable: powershell.exe
