# group_vars/production/windows_servers/script_vars.yml
---
    - name: Clone private Git repository
      win_shell: |
        if (Test-Path -Path "{{ temp_folder }}") {
          Remove-Item -Path "{{ temp_folder }}" -Recurse -Force
        }
        git clone "{{ git_repo_url | regex_replace('https://', 'https://'+git_access_token+'@') }}" "{{ temp_folder }}"
      args:
        executable: powershell.exe

    - name: Copy SetWinDriveLetter to temp
      win_shell: |
        Copy-Item -Path "{{ temp_folder }}{{ SetDriveLetter_script_path }}" -Destination "{{ temp_path }}" -Force
      args:
        executable: powershell.exe

    - name: Execute PowerShell script
      win_shell: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        . "{{ temp_path }}\{{ SetDriveLetter_script_name }}"
      args:
        executable: powershell.exe

    - name: Delete cloned Git repository
      win_shell: Remove-Item -Path "{{ temp_folder }}" -Recurse -Force
      args:
        executable: powershell.exe

    - name: Delete PowerShell script file
      win_shell: Remove-Item -Path "{{ temp_path }}\{{ SetDriveLetter_script_name }}" -Force
      args:
        executable: powershell.exe
