---
include_tempfolder_tasks: false
include_python_tasks: false
include_git_tasks: false
include_drive_letter_tasks: true
include_setup_disk_tasks: true
include_GitCloneAnsible_tasks: true
include_run_py_script_tasks: true
include_AddXmlElement_tasks: true
include_RMGitCloneAnsible_tasks: true

python_installer_url: "https://www.python.org/ftp/python/3.12.0/python-3.12.0-amd64.exe"
python_installer: "{{ temp_path }}\\python_installer.exe"
python_installation_check: "C:\\Python312\\python.exe"


git_installer_url: "https://github.com/git-for-windows/git/releases/download/v2.43.0.windows.1/Git-2.43.0-64-bit.exe"
git_installer_path: "{{ temp_path }}\\GitInstaller.exe"

git_repo_url: "https://github.com/movvamanoj/Ansible-P1.git"
git_access_token: "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"


ChangeWinDriveLetter_script_path: "\\roles\\windows_servers_role\\files\\ChangeWinDriveLetter.ps1"
ChangeWinDriveLetter_script_name: "ChangeWinDriveLetter.ps1"

SetupAutoWinDisk_script_name: "wktest2.ps1" #"SetupAutoWinDisk.ps1"
SetupAutoWinDisk_script_path: "\\roles\\windows_servers_role\\files\\wktest2.ps1"

AddXmlElement_script_name: "AddXmlElement.ps1"
AddXmlElement_script_path: "\\roles\\windows_servers_role\\files\\AddXmlElement.ps1"

# run_py_script_name: "run_py_script.py"
# run_py_script_path: "\\roles\\windows_servers_role\\files\\run_py_script.py"
ansible_project_path: "/home/mmanoj/Ansible-P1"
py_script_path: "roles/windows_servers_role/files/run_py_script.py"
py_script_output_path: "/home/mmanoj/Ansible-P1/roles/windows_servers_role/files/output_file.txt"
temp_path: "C:\\Temp"
temp_folder: "C:\\Temp\\Win-Powershell"
